In [1]:
import numpy as np

#### test row col access

In [2]:
#board = np.full([9,9], 0)
board = np.random.randint(10, size=(9, 9))
board

array([[6, 6, 0, 9, 1, 0, 2, 0, 0],
       [3, 5, 7, 3, 4, 9, 7, 5, 7],
       [2, 3, 7, 2, 9, 3, 7, 5, 9],
       [5, 0, 4, 1, 1, 0, 7, 1, 3],
       [1, 8, 1, 3, 7, 2, 0, 2, 8],
       [4, 3, 1, 3, 7, 8, 9, 0, 4],
       [1, 3, 2, 4, 5, 3, 7, 2, 5],
       [1, 2, 3, 5, 4, 7, 8, 3, 5],
       [7, 1, 5, 7, 5, 0, 1, 8, 6]])

In [43]:
print(board[0:3,0:3])
i = 2
if i in board[0:3,0:3]:
    print("true")
else:
    print("false")

[[6 6 0]
 [3 5 7]
 [2 3 7]]
true


In [44]:
print("row 0:", board[0])
print("row 1:", board[1])
print("row 4:", board[4])
print("col 0:", board[:, 0])
print("col 1:", board[:, 1])
print("1. 3X3:", board[0:3,0:3])
print("2. 3X3:", board[3:6,3:6])

row 0: [6 6 0 9 1 0 2 0 0]
row 1: [3 5 7 3 4 9 7 5 7]
row 4: [1 8 1 3 7 2 0 2 8]
col 0: [6 3 2 5 1 4 1 1 7]
col 1: [6 5 3 0 8 3 3 2 1]
1. 3X3: [[6 6 0]
 [3 5 7]
 [2 3 7]]
2. 3X3: [[1 1 0]
 [3 7 2]
 [3 7 8]]


####### 

In [78]:
board_new = np.full([9,9], 0)
board_new

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [79]:
def is_valid(board, row, col, num):
    row_coordinates = ()
    col_coordinates = ()
    if row in [0,1,2]: row_coordinates = 0, 3
    if row in [3,4,5]: row_coordinates = 3, 6
    if row in [6,7,8]: row_coordinates = 6, 9
        
    if col in [0,1,2]: col_coordinates = 0, 3
    if col in [3,4,5]: col_coordinates = 3, 6
    if col in [6,7,8]: col_coordinates = 6, 9
        
    #print("row_coordinates:", row_coordinates)
    #print("col_coordinates:", col_coordinates)
    #print("required 3X3 block:", 
    #      board[row_coordinates[0]:row_coordinates[1], col_coordinates[0]:col_coordinates[1]])

    if num in list(board[row]):
        return False
    elif num in list(board[:,col]):
        return False
    elif num in board[row_coordinates[0]:row_coordinates[1], col_coordinates[0]:col_coordinates[1]]:
        return False
    else:
        return True

In [80]:
for row in range(1, 10):
    for col in range(1, 10):
        for num in range(1, 10):
            if is_valid(board_new, row-1, col-1, num):
                board_new[row-1][col-1] = num
                break

In [81]:
board_new

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [4, 5, 6, 1, 2, 3, 0, 0, 0],
       [7, 8, 9, 0, 0, 0, 1, 2, 3],
       [2, 1, 4, 3, 6, 5, 8, 7, 0],
       [3, 6, 5, 2, 1, 4, 9, 0, 0],
       [8, 7, 0, 9, 0, 0, 2, 1, 4],
       [5, 3, 1, 6, 4, 2, 0, 9, 7],
       [6, 4, 2, 5, 3, 1, 0, 0, 8],
       [9, 0, 7, 8, 0, 0, 3, 4, 1]])

In [72]:
is_valid(board_new, 4-1, 5-1, 6)    #board, row, col, num

False